### ISSUE TITLE
robustness

### ISSUE THREAD

**Issue by andreasschulze** [sys4/tlsrpt#24]
when calling tlsrpt-* scripts without any parameter, users should see a meaningful message. Currently, python Traceback happen.

```
# tlsrpt-reporter 
Traceback (most recent call last):
  File "/usr/local/bin/tlsrpt-reporter", line 8, in <module>
    sys.exit(tlsrpt_reporter_main())
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1333, in tlsrpt_reporter_main
    reporter.run_loop()
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1157, in run_loop
    self.send_out_reports()
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1106, in send_out_reports
    if self.send_out_report(day, dom, d_r_id, uniqid, destination, report):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1088, in send_out_report
    return self.send_out_report_to_mail(day, dom, d_r_id, uniqid, destination, zreport)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1016, in send_out_report_to_mail
    msg.add_header("Message-ID", email.utils.make_msgid(domain=msg["From"].groups[0].addresses[0].domain))
                                                               ~~~~~~~~~~~~~~~~~~^^^
IndexError: tuple index out of range
```

reason in this case: contact_info was unset

```
# tlsrpt-fetcher  
Usage: %s day [domain]
root@tlsrpt-receiver:/# tlsrpt-receiver 
Traceback (most recent call last):
  File "/usr/local/bin/tlsrpt-receiver", line 8, in <module>
    sys.exit(tlsrpt_receiver_main())
             ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/pytlsrpt/tlsrpt.py", line 1222, in tlsrpt_receiver_main
    raise Exception("No receiver_socketname configured")
Exception: No receiver_socketname configured
```

reason here: receiver_socketname was unset

**Comment by uwekamper** [comment]
The Python 'argparse' library can display a help text ("Usage info") when required arguments are omitted:

- https://docs.python.org/3/howto/argparse.html
- https://docs.python.org/3/library/argparse.html
